appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: jnAom9fxEUxDzFFfHVjCHcaw50AlBObYQNpFje04Pc9N1zo/dpeOcpadWLUGvTcKJGcF5f2clreLdIaF3sBjQh3mUgP4aphKIS0LG6k4XsDZJXqCwlRKxMC3OvuP8TEVJALvc979/RqNxuLRQSiajiNzkayxCLUtage0hsN40rPp6YB72XFHmczHtFdVYV9OnWUcFcAJlxShTdbBLkA9on2OuEmOrsHyeegrgLlfxT2kDjnnMboqg/6oFR0/BqxkXK0daEq5gADVDGAczOU0Wb2bUYsVWbJKWbDgG5Mm3HBrIs7TB76wEruvmIiv2vPslsJYmvM7KUJP/heH5RDytmCVtWHIxTWS64O+AX0mQZxPltbqiN3P/1a9XKdDS6ZKs41caHMdvYI4sAyFZk1+ic67s5MWfhnIk62V6OX8geFkKPJq+dArL9gagh+5q90ZKqdE/c9uRDK/faLjpmRqDE7ITxBFBPlP16RCmoCPw4D+cz8fodV+Uvm2ZjlCn/pZ20oTvBc4CG4GQCeBr9f6OdJTN6BALhu6WdM6yAE1sZYLWwjRiJpg5Bx9NMcr5seHILWbtVleRll7lR9y+UKnJFoNA8Z05quwAbRtOPaUjtkPaOtVjvbQb2ni9EkwJ0GBCSAriOHd7ZtBY2kqgW6x1ZLJl4KwuDMpHoU3MZYfZrw=}
