travis:
  secure:
    BINSTAR_TOKEN: MBc1rFscGYor5T5S+lwSR//bsUBYyV/KKSz2Sjl4t37JDTbm7bcagC6eRBu6y6FjIcs2I50IA94Nl6PwgmwPQQR9QjTYs1ZkqqvW++o3gDgg/KDzuvuiiiW+18bKi129H1gPJj9XfqJo0hzsFQG6mSx/GtQK8I9dO8miR356Zx6QQZtB8excjzp/NPi94na6Ku6zq/B6EgIL5YNgewZcPe0eF5HyhWCwTF6Ue/9fpVWDjHtbD8SgiPG6K3cUJpPSWQK3bco/rtx4P7if6SqQ20pc/INOE/19Nh8QQ7wXL/qtggKGKTzGWmSdZYXZyQ9J1gSPHGh97FOsLok9z3ujeaU5hhQiy+b6O6rwnbEzGZ5XspfxzyyhsE7ksOCGlmVaYEOfY7FqOBnA0QpSLegGlojwNYm1lXynXFosWwD+G8qlLi0369AeJrn4YEL/VnMOPS9RYSRQBpgVWN+cOWvfMFISeIezWdAgxS3Vm7AC7QC87OxjzmeckoQWhB4FZJ+2A8G5+I5yEo1VRMTtfnAOJdgMofqy5VKbMVCHa6IsvatBNvd4iQq5llB3dILivgn0aUaL9AzpRtUul5TAAQdhPZncuh/W4eC1MARqZaSLfkam2H3QmoNa80RCHsWP0epqElm4uAx3xqAnuS5RQo8tCYgKaqI1IYVqkxMW/3RpFFI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
